name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.11
      uses: actions/setup-node@v1
      with:
        node-version: 12.11
    - name: npm install, lint, and build
      run: |
        npm install
        npm run lint
        npm run build
      env:
        CI: true
