name: Node CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.11
        uses: actions/setup-node@v1
        with:
          node-version: 12.11
      - name: npm install, lint, and build
        run: |
          npm install
          npm run lint
          npm run build
      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: malware-revealer/malware-revealer
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./dist
